---
exp_name: GRAN
exp_dir: exp/complete_graph_no_dropout
runner: GNNRunner
use_gpu: true
device: cuda:0
gpus: [0]
seed: 1234
dataset:
  loader_name: CompleteGraphData
  name: grid
  data_path: data/
  node_order: DFS # k_core/BFS/degree_decent
  train_ratio: 0.8
  dev_ratio: 0.2
  num_fwd_pass: 1
  is_save_split: false
  is_overwrite_precompute: False
model:
  name: GNNStack
  model_type: GCN
  input_one_feature: False
  dropout: 0.5
  num_head: 5
  max_num_nodes: 361
  hidden_dim: 128
  embedding_dim: 128
  num_GraphGNN_layers: 3
  num_canonical_order: 1
  dimension_reduce: true
train:
  optimizer: Adam
  lr_decay: 0.3
  lr_decay_epoch: [100000000] # no decay
  num_workers: 0
  max_epoch: 1000
  batch_size: 1
  display_iter: 10
  snapshot_epoch: 100
  valid_epoch: 50
  lr: 1.0e-4
  wd: 0.
  momentum: 0.9
  shuffle: true
  is_resume: false
  resume_epoch: 5000
test:
  batch_size: 1
  num_workers: 0
  is_vis: true
  is_single_plot: true # visualize `num_vis` samples in a single image
  num_vis: 20
  vis_num_row: 5 # visualize `num_vis` samples in `vis_num_row` rows
  better_vis: true
  test_model_dir: exp/GRAN_grid_gat/GATGRANMixtureBernoulli_grid_2019-Dec-07-22-31-46_8190/
  test_model_name: model_snapshot_0003000.pth
