---
exp_name_prefix: 'G_instance_norm'
exp_dir: exp/GAN_grid_small  # TODO: change
runner: GANRunner
use_gpu: true
device: cuda:0
gpus: [0]
seed: 1234
dataset:
  loader_name: GANData
  name: grid_small
  max_m: 8
  max_n: 8
  data_path: data/
  node_order: default # k_core/BFS/degree_decent
  train_ratio: 0.8
  dev_ratio: 0.2
  num_subgraph_batch: 50 # number of subgraphs per mini-batch
  num_fwd_pass: 1
  is_save_split: false
  is_overwrite_precompute: true
model:
  lambda_rote: 1
  nz: 16
  name: DCGAN
  netG: DCGAN
  netD: basic
  ngf: 16
  ndf: 16
  norm_G: instance
  norm_D: instance
  gan_mode: lsgan
  final_activation: tanh
  pool_size: 50
  sparsity: 0.
  is_sym: true  # is undirected graph
  max_num_nodes: 64
  num_canonical_order: 1
train:
  optimizer: Adam
  lr_decay: 0.3
  lr_decay_epoch: [100000000] # no decay
  num_workers: 0
  max_epoch: 3000
  batch_size: 16
  display_iter: 10
  snapshot_epoch: 100
  lr: 0.0001
  beta1: 0.5
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  is_resume: false
  resume_epoch: 5000
  resume_dir: # exp/GRAN/your_exp_folder
  resume_model: model_snapshot_0005000.pth
test:
  batch_size: 1
  num_workers: 0
  num_test_gen: 10 # number of generated samples
  is_vis: true
  is_single_plot: true # visualize `num_vis` samples in a single image
  num_vis: 10
  vis_num_row: 5 # visualize `num_vis` samples,`vis_num_row` per rows
  better_vis: True
  test_model_dir: exp/GRAN_grid_gat_att_softmax/GATGRANMixtureBernoulli_grid_2019-Dec-07-22-46-01_4481  # TODO: change
  test_model_name: model_snapshot_0003000.pth  # TODO: may change
  hard_multi: true
