---
exp_name_prefix: no_complete_soft
exp_dir: exp/GRAN_grid_gat_att_softmax  # TODO: change
runner: GranRunner
use_gpu: true
device: cuda:0
gpus: [0]
seed: 1234
dataset:
  loader_name: GRANData
  name: grid
  data_path: data/
  node_order: DFS # k_core/BFS/degree_decent
  train_ratio: 0.8
  dev_ratio: 0.2
  num_subgraph_batch: 50 # number of subgraphs per mini-batch
  num_fwd_pass: 1
  has_node_feat: false
  is_save_split: false
  is_sample_subgraph: true # set to true if you want to sample subgraphs
  is_overwrite_precompute: false
model:
  name: GATGRANMixtureBernoulli
  num_head: 5
  att_use_softmax: True
  num_mix_component: 20  # # mix Bernoulli
  is_sym: true  # is undirected graph
  block_size: 1
  sample_stride: 1
  max_num_nodes: 361
  hidden_dim: 128
  embedding_dim: 128
  num_GNN_layers: 7
  num_GNN_prop: 1
  num_canonical_order: 1
  dimension_reduce: true
  has_attention: true
  edge_weight: 1.0e+0
#complete_graph_model:
#  name: GNNStack
#  model:
#    dimension_reduce: true
#    dropout: 0.0
#    embedding_dim: 128
#    hidden_dim: 128
#    max_num_nodes: 361
#    model_type: GCN
#    num_GraphGNN_layers: 3
#    num_canonical_order: 1
#    num_head: 5
#  # use train graphs only
#  test_model_dir: exp/complete_graph_no_dropout/GNNStack_grid_2019-Dec-09-01-39-36_30029
#  test_model_name: model_snapshot_0000802.pth
##  # use all graphs
##  test_model_dir: exp/complete_graph_whole_graphs/GNNStack_grid_2019-Dec-09-02-17-41_17271
##  test_model_name: model_snapshot_0000635.pth
train:
  optimizer: Adam
  lr_decay: 0.3
  lr_decay_epoch: [100000000] # no decay
  num_workers: 0
  max_epoch: 3000
  batch_size: 1
  display_iter: 10
  snapshot_epoch: 100
  valid_epoch: 50
  lr: 1.0e-4
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  is_resume: false
  resume_epoch: 5000
  resume_dir: # exp/GRAN/your_exp_folder
  resume_model: model_snapshot_0005000.pth
test:
  batch_size: 20
  num_workers: 0
  num_test_gen: 20 # number of generated samples
  is_vis: true
  is_single_plot: true # visualize `num_vis` samples in a single image
  is_test_ER: false # test Erdos-Renyi baseline
  num_vis: 20
  vis_num_row: 5 # visualize `num_vis` samples,`vis_num_row` per rows
  better_vis: True
  test_model_dir: exp/GRAN_grid_gat_att_softmax/GATGRANMixtureBernoulli_grid_2019-Dec-07-22-46-01_4481  # TODO: change
  test_model_name: model_snapshot_0003000.pth  # TODO: may change
  hard_multi: false
