---
exp_name_prefix: 'smaller_kcore'
exp_dir: exp_DD/GRAN_gat_att_softmax_kcore
runner: GranRunner
use_gpu: true
device: cuda:0
gpus: [0]
seed: 1234
dataset:
  loader_name: GRANData
  name: DD
  data_path: data/
  node_order: k_core # k_core/BFS/degree_decent
  train_ratio: 0.8
  dev_ratio: 0.2
  num_subgraph_batch: 2 # number of subgraphs per mini-batch
  num_fwd_pass: 1
  has_node_feat: false
  is_save_split: false
  is_sample_subgraph: true # set to true if you want to sample subgraphs
  is_overwrite_precompute: false
model:
  name: GATGRANMixtureBernoulli
  num_head: 5
  att_use_softmax: True
  num_mix_component: 20  # # mix Bernoulli
  is_sym: true  # is undirected graph
  block_size: 1
  sample_stride: 1
  max_num_nodes: 500
  hidden_dim: 512
  embedding_dim: 256
  num_GNN_layers: 7
  num_GNN_prop: 1
  num_canonical_order: 1
  dimension_reduce: true
  has_attention: true
  edge_weight: 1.0e+0
train:
  optimizer: Adam
  lr_decay: 0.1
  lr_decay_epoch: [100000000] # no decay
  num_workers: 8
  max_epoch: 5000
  batch_size: 16
  display_iter: 10
  snapshot_epoch: 100
  valid_epoch: 50
  lr: 1.0e-4
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  is_resume: false
  resume_epoch: 400
  resume_dir: exp_DD/GRAN_gat_att_softmax/_GATGRANMixtureBernoulli_DD_2019-Dec-09-11-25-15_25613
  resume_model: model_snapshot_0000400.pth
test:
  batch_size: 20
  num_workers: 0
  num_test_gen: 183 # number of generated samples
  is_vis: true
  is_single_plot: false # visualize `num_vis` samples in a single image
  is_test_ER: false # test Erdos-Renyi baseline
  num_vis: 20
  vis_num_row: 5 # visualize `num_vis` samples in `vis_num_row` rows
  better_vis: true
  test_model_dir: ''# TODO: set
  test_model_name: model_snapshot_0003000.pth
  hard_multi: True  # TODO: set
